/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import java.awt.Point;

import Shapes.*;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author youssef
 */

@SuppressWarnings("unused")
public class LineSegmentWindow extends javax.swing.JFrame implements Node {

    private Canvas items;
    private Color color = Color.BLACK;
    @SuppressWarnings("rawtypes")
    private JComboBox Shapes;
    Node parent;

    /**
     * Creates new form LineSegment
     */
    public LineSegmentWindow() {
        initComponents();
        this.setTitle("Add Line Segment");
    }

    @SuppressWarnings("rawtypes")
    public LineSegmentWindow(Canvas items, JComboBox Shapes) {
        initComponents();
        this.setTitle("Line Segment");
        this.items = items;
        this.Shapes = Shapes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startX = new javax.swing.JLabel();
        startY = new javax.swing.JLabel();
        endX = new javax.swing.JLabel();
        endY = new javax.swing.JLabel();
        startPointX = new javax.swing.JTextField();
        startPointY = new javax.swing.JTextField();
        endPointX = new javax.swing.JTextField();
        endPointY = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        borderColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        startX.setBackground(new java.awt.Color(51, 255, 51));
        startX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startX.setText("Start X");

        startY.setBackground(new java.awt.Color(51, 255, 51));
        startY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startY.setText("Start Y");

        endX.setBackground(new java.awt.Color(51, 255, 51));
        endX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endX.setText("End X");

        endY.setBackground(new java.awt.Color(51, 255, 51));
        endY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endY.setText("End Y");

        startPointX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        startPointX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPointXActionPerformed(evt);
            }
        });

        startPointY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        startPointY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPointYActionPerformed(evt);
            }
        });

        endPointX.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        endPointY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endPointY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPointYActionPerformed(evt);
            }
        });

        okButton.setBackground(new java.awt.Color(0, 0, 0));
        okButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        okButton.setForeground(new java.awt.Color(255, 255, 255));
        okButton.setText("Add");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        borderColor.setBackground(new java.awt.Color(0, 0, 0));
        borderColor.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        borderColor.setForeground(new java.awt.Color(255, 255, 255));
        borderColor.setText("Set Color");
        borderColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(startX)
                                        .addComponent(startY)
                                        .addComponent(endX)
                                        .addComponent(endY, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(borderColor))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(startPointX, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startPointY, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endPointX, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endPointY, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(50, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(borderColor,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(startX)
                                                        .addComponent(startPointX,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(startY)
                                                        .addComponent(startPointY,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(endX)
                                                        .addComponent(endPointX, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(endY)
                                                        .addComponent(endPointY, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 75, Short.MAX_VALUE)))
                                .addContainerGap(15, Short.MAX_VALUE)));

        layout.linkSize(javax.swing.SwingConstants.VERTICAL,
                new java.awt.Component[] { endPointX, endPointY, startPointX, startPointY });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startPointXActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startPointXActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_startPointXActionPerformed

    @SuppressWarnings("unchecked")
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        try {
            Integer.valueOf(startPointX.getText());
            Integer.valueOf(startPointY.getText());
            Integer.valueOf(endPointX.getText());
            Integer.valueOf(endPointY.getText());
            ShapeAbstract line = new LineSegment(
                    new Point(Integer.parseInt(startPointX.getText()), Integer.parseInt(startPointY.getText())),
                    new Point(Integer.parseInt(endPointX.getText()), Integer.parseInt(endPointY.getText())));
            line.setFillColor(color);
            items.addShape(line);
            Shapes.addItem("line_" + VectorDrawingApplication.lineCounter);
            VectorDrawingApplication.lineCounter++;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input!");
        } finally {
            startPointX.setText("");
            startPointY.setText("");
            endPointX.setText("");
            endPointY.setText("");
            this.setVisible(false);
            ((JFrame) getParentNode()).setVisible(true);
            items.repaint();
            this.color = Color.BLACK;

        }
    }// GEN-LAST:event_okButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);
        startPointX.setText("");
        startPointY.setText("");
        endPointX.setText("");
        endPointY.setText("");
    }// GEN-LAST:event_formWindowClosing

    private void endPointYActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_endPointYActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_endPointYActionPerformed

    private void borderColorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_borderColorActionPerformed
        // TODO add your handling code here:
        this.color = JColorChooser.showDialog(this, "Choose line color", null);
    }// GEN-LAST:event_borderColorActionPerformed

    private void startPointYActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startPointYActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_startPointYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LineSegmentWindow.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LineSegmentWindow.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LineSegmentWindow.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LineSegmentWindow.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LineSegmentWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColor;
    public javax.swing.JTextField endPointX;
    public javax.swing.JTextField endPointY;
    private javax.swing.JLabel endX;
    private javax.swing.JLabel endY;
    private javax.swing.JButton okButton;
    public javax.swing.JTextField startPointX;
    public javax.swing.JTextField startPointY;
    private javax.swing.JLabel startX;
    private javax.swing.JLabel startY;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
}
